version: "3.0"
services:
  limesurvey:
    container_name: limesurvey
    build:
      context: apache/
      dockerfile: Dockerfile
    volumes:
      - ./limesurvey/config:/var/www/html/application/config
      - ./limesurvey/apache2:/etc/apache2
    links:
      - lime-db
    depends_on:
      - lime-db
    ports:
      - "8888:80"
    environment:
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=1ns!ghts"
      - "ADMIN_PASSWORD=1ns!ghts"
  lime-db:
    image: mysql:5.7
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_PASSWORD=1ns!ghts"
      - "MYSQL_ROOT_PASSWORD=1ns!ghts"
    volumes:
      - /data/limesurvey/db:/var/lib/mysql
